sonar.projectKey=mobile-final-project
sonar.projectName=mobile-final-project
sonar.sources=backend/src/game
sonar.tests=backend/src/game
sonar.test.inclusions=backend/src/game/**/*.spec.ts
sonar.javascript.lcov.reportPaths=backend/coverage/lcov.info