sonar.projectKey=mobile-final-project
sonar.projectName=mobile-final-project
sonar.sources=backend/src
sonar.tests=backend/src
sonar.test.inclusions=backend/src/**/*.spec.ts
sonar.javascript.lcov.reportPaths=backend/coverage/lcov.info