sonar.projectKey=mobile-final-project
sonar.projectName=mobile-final-project

sonar.projectBaseDir=backend

sonar.sources=src/game
sonar.tests=src/game
sonar.test.inclusions=src/game/**/*.spec.ts

sonar.exclusions=src/game/**/*.spec.ts,src/game/**/*.smoke.ts,src/game/fixtures/**,src/game/index.ts

sonar.javascript.lcov.reportPaths=coverage/lcov.info